    # Default LED strip configuration:
    # any parameters that for sure don't need to be changed by settings can be defaulted in the constructor and removed from main()
    LED_COUNT : 60        # Number of LED pixels.
    LED_PIN : 18          # GPIO pin connected to the pixels (18 uses PWM!).
    LED_FREQ_HZ : 800000  # LED signal frequency in hertz (usually 800khz)
    LED_DMA : 10          # DMA channel to use for generating signal (try 10)
    LED_BRIGHTNESS : 200  # Set to 0 for darkest and 255 for brightest
    LED_INVERT : False    # True to invert the signal (when using NPN transistor level shift)
    LED_CHANNEL : 0       # set to '1' for GPIOs 13, 19, 41, 45 or 53
    ROTATION : 52

    #replace with file i/o
    COLOR_0 : RED                 #seconds
    COLOR_1 : GOLD                  #minute fill
    COLOR_2 : LIGHT_BLUE            #hour ticks
    COLOR_3 : DARK_MAGENTA                  #current hour